#!/bin/bash

devenv_requirements() {
    return 0;
}

devenv_load() {
    mkdir -p "${HOME}/Development/Projects"
    mkdir -p "${HOME}/Development/Boxes"
    mkdir -p "${HOME}/Development/Experiments"

    alias p="cd ${HOME}/Development/Projects"
    alias b="cd ${HOME}/Development/Boxes"
    alias e="cd ${HOME}/Development/Experiments"
}
