#!/bin/bash

makefile_requirements() {
    return 0;
}

makefile_load() {
    alias make1mb='mkfile 1m ./1mb.dat && echo "New file 1mb.dat created."'            # Creates a file of 1mb size (all zeros)
    alias make5mb='mkfile 5m ./5mb.dat && echo "New file 5mb.dat created."'            # Creates a file of 5mb size (all zeros)
    alias make10mb='mkfile 10m ./10mb.dat && echo "New file 10mb.dat created."'        # Creates a file of 10mb size (all zeros)
    alias make100mb='mkfile 100m ./100mb.dat && echo "New file 100mb.dat created."'    # Creates a file of 100mb size (all zeros)
    alias make1gb='mkfile 1000m ./1gb.dat && echo "New file 1gb.dat created."'         # Creates a file of 1gb size (all zeros)
    alias make10gb='mkfile 10000m ./10gb.dat && echo "New file 10gb.dat created."'     # Creates a file of 10gb size (all zeros)
    alias make100gb='mkfile 100000m ./100gb.dat && echo "New file 100gb.dat created."' # Creates a file of 100gb size (all zeros)
}